options:
  api_port:
    type: int
    description: InfluxDB API port
    default: 8086
  admin_port:
    type: int
    description: InfluxDB Admin HTTP port
    default: 8083
  graphite_port:
    type: int
    description: InfluxDB Graphite API port
    default: 8217
  graphite_dbname:
    type: string
    description: Graphite DB name
    default: "data"

